# Generated by Django 3.1.5 on 2021-01-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('to apply', 'to apply'), ('applied', 'applied'), ('ongoing', 'ongoing'), ('rejected', 'rejected'), ('offer', 'offer')], default='to apply', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('applied_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
