# Generated by Django 3.1.5 on 2021-01-13 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Byte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('weightage', models.CharField(choices=[('CHILL', 'CHILL'), ('NORMAL', 'NORMAL'), ('ASAP', 'ASAP'), ('DUE', 'DUE')], default='CHILL', max_length=10)),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('ACTIVE', 'ACTIVE'), ('REVIEW', 'REVIEW'), ('FINISHED', 'FINISHED')], default='TODO', max_length=10)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.arena')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('arena', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='team.arena')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=256)),
                ('byte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.byte')),
            ],
        ),
        migrations.AddField(
            model_name='byte',
            name='user_info',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='team.userinfo'),
        ),
    ]
