# Generated by Django 3.1.5 on 2021-01-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20210113_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='arena',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='arena',
            field=models.ManyToManyField(blank=True, null=True, to='team.Arena'),
        ),
    ]
