# Generated by Django 3.1.5 on 2021-01-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20210113_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('to apply', 'to apply'), ('applied', 'applied'), ('ongoing', 'ongoing'), ('rejected', 'rejected'), ('offer', 'offer')], default='to apply', max_length=20)),
                ('notes', models.TextField()),
                ('applied_date', models.DateField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='byte',
            name='arena',
        ),
        migrations.RemoveField(
            model_name='byte',
            name='user_info',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='byte',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='arena',
        ),
        migrations.DeleteModel(
            name='Arena',
        ),
        migrations.DeleteModel(
            name='Byte',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
