# Generated by Django 3.1.5 on 2021-01-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20210131_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='applied_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opening',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
